version: '1.0'

services:

  postgres-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    
    ports:
      5432:5432
  
volumes:
  db-data:



