POST http://localhost:8080/api/users/register HTTP/1.1
content-type: application/json

{
"user": {
    "username":"juniorgreen",
    "firstName":"Junior",
    "middleName": "Christopher",
    "lastName":"Green",
    "email":"juniorgreen9185@hotmail.com",
    "dateOfBirth":"2002-05-13",
    "phoneNumber":"647-571-8450",
    "gender":"Male"
    },
"password": "XsTj7uBH#xWuAR5"
}

###

GET http://localhost:8080/api/users HTTP/1.1

###

GET http://localhost:8080/api/users/juniorgreen HTTP/1.1

###

DELETE http://localhost:8080/api/users?id=82f0d480-cd88-4eeb-b290-c99411e6ebb4 HTTP/1.1

###

PUT http://localhost:8080/api/users?id=82f0d480-cd88-4eeb-b290-c99411e6ebb4 HTTP/1.1
content-type: application/json

{
"email":"juniororange9185@hotmail.com",
"username": "juniororange9185"
}

###

PUT http://localhost:8080/api/auth/6cca6416-1403-4cb0-90cc-827eedce9351 HTTP/1.1

"939==391vm3149j=#*_+THn3-"